### ISSUE TITLE
更换 Polyfiller Docker 卷元数据库

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/Polyfiller#2]
## 相关资料

- issue：juicedata/docker-volume-juicefs#37
- PR：juicedata/juicefs#4484

## 建议方案

在以下配置中新增独立数据库服务：

https://github.com/kaiyuanshe/Polyfiller/blob/60130fc53db9038c564ab02ce14a8898dc3ce172/docker-compose.yml#L14-L34

再配置到：

https://github.com/kaiyuanshe/Polyfiller/blob/60130fc53db9038c564ab02ce14a8898dc3ce172/docker-compose.yml#L8

**Comment by tianheg** [comment]
是不是换成 [How to Set Up Object Storage | JuiceFS Document Center](https://juicefs.com/docs/community/reference/how_to_set_up_object_storage/#supported-object-storage) 这里提到的其他数据库，那换成 Azure Blob Storage 可以吗，我们的服务不都是部署在 Azure 上的吗

**Comment by TechQuery** [comment]
> 是不是换成 [How to Set Up Object Storage | JuiceFS Document Center](https://juicefs.com/docs/community/reference/how_to_set_up_object_storage/#supported-object-storage) 这里提到的其他数据库，那换成 Azure Blob Storage 可以吗，我们的服务不都是部署在 Azure 上的吗

不是，我们就是用 JuiceFS 来封装 Blob Storage 为文件系统的。现在是要更换它的元数据库，不是文件数据库。

参考：https://juicefs.com/docs/community/databases_for_metadata

**Comment by TechQuery** [comment]
@luojiyin1987 尝试按以下方式自行包装 **Docker 数据卷容器**来解决这个问题：
https://github.com/juicedata/docker-volume-juicefs/issues/39#issuecomment-2003621974
